class UserMailer < ActionMailer::Base
  default from: "binaryskipper@gmail.com"

  # REVIEW: please remove unnecessary comments that gets generated by generators.

  # Subject can be set in your I18n file at config/locales/en.yml
  # with the following lookup:
  #
  #   en.user_mailer.signup_confirmation.subject
  #
  def signup_confirmation(user)
    @user = user

    mail to: @user.email
  end
end
